# Generated by Django 5.2.5 on 2025-09-06 08:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='last_report_reason',
            field=models.CharField(blank=True, choices=[('spam', 'Spam or misleading'), ('inappropriate', 'Inappropriate content'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reel',
            name='reports',
            field=models.ManyToManyField(blank=True, help_text='Users who reported this reel.', related_name='reported_reels', to=settings.AUTH_USER_MODEL),
        ),
    ]
