# Generated by Django 5.2.5 on 2025-09-07 09:45

import core.utils.upload_paths
import core.utils.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0002_reel_last_report_reason_reel_reports'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='is_banned',
            field=models.BooleanField(default=False, help_text='Hide this reel if it violates policies'),
        ),
        migrations.AlterField(
            model_name='reel',
            name='last_report_reason',
            field=models.CharField(blank=True, choices=[('spam', 'Spam or misleading'), ('inappropriate', 'Inappropriate content'), ('other', 'Other')], help_text='Stores the last reported reason', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reel',
            name='reports',
            field=models.ManyToManyField(blank=True, help_text='Users who reported this reel', related_name='reported_reels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reel',
            name='shares',
            field=models.PositiveIntegerField(default=0, help_text='Increment when reel is shared'),
        ),
        migrations.AlterField(
            model_name='reel',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Auto-generated thumbnail from video', null=True, upload_to=core.utils.upload_paths.reel_thumbnail_upload_to, validators=[core.utils.validators.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='reel',
            name='user',
            field=models.ForeignKey(help_text='Owner of the reel', on_delete=django.db.models.deletion.CASCADE, related_name='reels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reel',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text='Auto-increment on each view'),
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='reel_audio/')),
                ('duration', models.FloatField(blank=True, help_text='Duration in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_from_reel', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reel',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reels', to='reels.audio'),
        ),
    ]
