# Generated by Django 5.2.5 on 2025-09-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0003_reel_is_banned_alter_reel_last_report_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='reach',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
