# Generated by Django 5.2.5 on 2025-09-08 06:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0004_reel_reach'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='share_comments', to='reels.comment'),
        ),
        migrations.AddField(
            model_name='share',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='share',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='saved_shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='share',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
