# Generated by Django 5.2.5 on 2025-09-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0005_share_comments_share_likes_share_saves_share_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='reel',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the reel', null=True),
        ),
        migrations.AddField(
            model_name='reel',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Optional hashtags for this reel', related_name='reels', to='reels.tag'),
        ),
    ]
