# Generated by Django 5.2.5 on 2025-09-15 12:45

import core.utils.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0006_tag_reel_description_reel_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='video_duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reel',
            name='video_size_mb',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='reel',
            name='video',
            field=models.FileField(help_text='Video file up to 15 seconds and 20 MB', upload_to=core.utils.upload_paths.reel_upload_to),
        ),
    ]
