# Generated by Django 5.2.5 on 2025-09-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0007_reel_video_duration_reel_video_size_mb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='is_ad',
            field=models.BooleanField(default=False, help_text='Marks this reel as an advertisement (only staff/company can set this).'),
        ),
    ]
