# Generated by Django 5.2.5 on 2025-09-04 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_options_remove_profile_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='genric_link',
            new_name='generic_link',
        ),
    ]
