# Generated by Django 5.2.5 on 2025-09-05 16:24

import core.utils.upload_paths
import core.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_genric_link_profile_generic_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='badge_earned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='badge_name',
            field=models.CharField(default='Blue Tick', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_share_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Optional profile picture.', null=True, upload_to=core.utils.upload_paths.user_avatar_upload_to, validators=[core.utils.validators.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='generic_link',
            field=models.URLField(blank=True, help_text='Optional  Instagram/Youtube profile link.', max_length=500, null=True, validators=[core.utils.validators.validate_http_url]),
        ),
    ]
