# Generated by Django 5.2.5 on 2025-09-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0001_initial'),
        ('users', '0006_profile_badge_earned_profile_badge_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hidden_reels',
            field=models.ManyToManyField(blank=True, help_text='Reels hidden by the user, will not appear in their feed.', related_name='hidden_by', to='reels.reel'),
        ),
    ]
