# Generated by Django 5.2.5 on 2025-09-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_is_banned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='badge_earned',
        ),
        migrations.AddField(
            model_name='profile',
            name='badge_type',
            field=models.CharField(blank=True, choices=[('silver', 'Silver'), ('gold', 'Gold'), ('black', 'Black')], max_length=10, null=True),
        ),
    ]
