# Generated by Django 5.2.5 on 2025-09-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_profile_badge_earned_profile_badge_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_reach',
            field=models.PositiveIntegerField(default=0, help_text="Sum of reach from all user's reels."),
        ),
    ]
