# Generated by Django 5.2.5 on 2025-09-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0006_tag_reel_description_reel_tags'),
        ('users', '0010_profile_total_reach'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='engaged_tags',
            field=models.ManyToManyField(blank=True, help_text='Tags the user interacts with or likes.', related_name='engaged_by_profiles', to='reels.tag'),
        ),
    ]
