# Generated by Django 5.2.5 on 2025-09-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_profile_engaged_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="strike_count",
            field=models.PositiveIntegerField(
                default=0, help_text="How many strikes this user has received."
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="temp_block_until",
            field=models.DateTimeField(
                blank=True,
                help_text="User is temporarily blocked until this datetime.",
                null=True,
            ),
        ),
    ]
