# Generated by Django 5.2.5 on 2025-09-24 11:15

import core.utils.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_user_strike_count_user_temp_block_until"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="qr_code",
            field=models.ImageField(
                blank=True,
                help_text="Optional QR code image for the user.",
                null=True,
                upload_to=core.utils.upload_paths.profile_qr_upload_to,
            ),
        ),
    ]
