# Generated by Django 5.2.5 on 2025-09-18 06:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='guess_max',
            field=models.PositiveIntegerField(default=100, help_text='Maximum number allowed to guess'),
        ),
        migrations.AddField(
            model_name='game',
            name='guess_min',
            field=models.PositiveIntegerField(default=1, help_text='Minimum number allowed to guess'),
        ),
        migrations.AlterUniqueTogether(
            name='gamesubmission',
            unique_together={('game', 'user')},
        ),
    ]
