# Generated by Django 5.2.5 on 2025-09-19 16:07

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_gamesubmission_options_game_duration_and_more'),
        ('reels', '0008_reel_is_ad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamesubmission',
            options={},
        ),
        migrations.AlterModelOptions(
            name='winnerhistory',
            options={'verbose_name': 'Winner History', 'verbose_name_plural': 'Winner Histories'},
        ),
        migrations.RemoveField(
            model_name='winnerhistory',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='hash_value',
            field=models.CharField(blank=True, editable=False, help_text='Hash of winning numbers (for fairness verification).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='salt',
            field=models.CharField(blank=True, editable=False, help_text='Random salt for hash generation.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='winning_numbers_encrypted',
            field=models.TextField(blank=True, editable=False, help_text='Encrypted winning numbers.', null=True),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='decrypted_winning_numbers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='winnerhistory',
            name='game_history',
            field=models.ForeignKey(blank=True, help_text='Link to the related GameHistory record.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='games.gamehistory'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the game.', null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=1), help_text='Game duration (default: 24 hours).'),
        ),
        migrations.AlterField(
            model_name='game',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='End time (auto-calculated on save).', null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='guess_max',
            field=models.PositiveIntegerField(default=100, help_text='Maximum guess number.'),
        ),
        migrations.AlterField(
            model_name='game',
            name='guess_min',
            field=models.PositiveIntegerField(default=1, help_text='Minimum guess number.'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(help_text='Image representing the reward.', upload_to='game_rewards/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the game is active or soft-deleted.'),
        ),
        migrations.AlterField(
            model_name='game',
            name='link',
            field=models.URLField(blank=True, help_text='Optional external link for the game.', null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='number_of_winners',
            field=models.PositiveIntegerField(default=1, help_text='Number of winners allowed.'),
        ),
        migrations.AlterField(
            model_name='game',
            name='reel',
            field=models.ForeignKey(blank=True, help_text='Optional reel linked to this game.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='reels.reel'),
        ),
        migrations.AlterField(
            model_name='game',
            name='reward_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('digital', 'Digital'), ('product', 'Product')], help_text='Type of reward offered.', max_length=20),
        ),
        migrations.AlterField(
            model_name='gamesubmission',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='games.game'),
        ),
        migrations.AlterField(
            model_name='gamesubmission',
            name='guessed_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='gamesubmission',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamesubmission',
            name='prize_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesubmission',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gamesubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='winnerhistory',
            name='claimed_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the reward was claimed/winner decided.'),
        ),
        migrations.AlterField(
            model_name='winnerhistory',
            name='number',
            field=models.PositiveIntegerField(help_text='The number guessed by the winner.'),
        ),
        migrations.AlterField(
            model_name='winnerhistory',
            name='prize_position',
            field=models.PositiveIntegerField(help_text="Winner's rank/position."),
        ),
        migrations.AlterField(
            model_name='winnerhistory',
            name='reward_description',
            field=models.TextField(blank=True, help_text='Description of the reward.', null=True),
        ),
        migrations.AlterField(
            model_name='winnerhistory',
            name='reward_image',
            field=models.ImageField(blank=True, null=True, upload_to='winner_rewards/'),
        ),
        migrations.AlterField(
            model_name='winnerhistory',
            name='reward_link',
            field=models.URLField(blank=True, help_text='Optional link for reward claim.', null=True),
        ),
        migrations.AlterField(
            model_name='winnerhistory',
            name='reward_type',
            field=models.CharField(help_text='Type of reward (cash/digital/product).', max_length=20),
        ),
        migrations.AlterField(
            model_name='winnerhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
