# Generated by Django 5.2.5 on 2025-09-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_gamesubmission_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='auto_close',
            field=models.BooleanField(default=True, help_text='Whether the game should auto-close when end_time is reached.'),
        ),
        migrations.AddField(
            model_name='game',
            name='auto_select_winner',
            field=models.BooleanField(default=True, help_text='Automatically select winners when game closes.'),
        ),
        migrations.AddField(
            model_name='game',
            name='winners_selected',
            field=models.BooleanField(default=False, help_text='Whether winners have already been selected.'),
        ),
    ]
