# Generated by Django 5.2.5 on 2025-09-20 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_game_auto_close_game_auto_select_winner_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="winnerhistory",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="winnerhistory",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="winnerhistory",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="winnerhistory",
            name="claim_deadline",
            field=models.DateTimeField(
                blank=True, help_text="Deadline for claiming the reward", null=True
            ),
        ),
        migrations.AddField(
            model_name="winnerhistory",
            name="is_claimed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="winnerhistory",
            name="reward_delivered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="winnerhistory",
            name="reward_delivery_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Deadline for creator to deliver reward",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="winnerhistory",
            name="claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="RewardMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional screenshot or proof",
                        null=True,
                        upload_to="reward_messages/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winner_history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="games.winnerhistory",
                    ),
                ),
            ],
        ),
    ]
