# Generated by Django 5.2.5 on 2025-09-20 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_remove_winnerhistory_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="winnerhistory",
            options={
                "permissions": [
                    ("can_mark_reward_delivered", "Can mark reward as delivered")
                ],
                "verbose_name": "Winner History",
                "verbose_name_plural": "Winner Histories",
            },
        ),
        migrations.AddField(
            model_name="winnerhistory",
            name="game",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to the original live Game.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="winner_histories",
                to="games.game",
            ),
        ),
    ]
