# Generated by Django 5.2.5 on 2025-09-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0007_alter_winnerhistory_options_winnerhistory_game"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="winnerhistory",
            options={
                "permissions": [
                    ("can_mark_claimed", "Can mark winner as claimed"),
                    ("can_mark_reward_delivered", "Can mark reward as delivered"),
                ],
                "verbose_name": "Winner History",
                "verbose_name_plural": "Winner Histories",
            },
        ),
    ]
