# Generated by Django 5.2.5 on 2025-09-20 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0008_alter_winnerhistory_options"),
        ("reels", "0008_reel_is_ad"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamehistory",
            name="reel_id",
        ),
        migrations.RemoveField(
            model_name="winningnumber",
            name="is_claimed",
        ),
        migrations.AddField(
            model_name="gamehistory",
            name="reel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reels.reel",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="reel",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional reel linked to this game.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games",
                to="reels.reel",
            ),
        ),
        migrations.AlterField(
            model_name="rewardmessage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="reward_messages/"
            ),
        ),
        migrations.AlterField(
            model_name="winnerhistory",
            name="game_history",
            field=models.ForeignKey(
                help_text="Link to the related GameHistory record.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="winners",
                to="games.gamehistory",
            ),
        ),
        migrations.AlterField(
            model_name="winnerhistory",
            name="user",
            field=models.ForeignKey(
                help_text="User who won this game.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
