# Generated by Django 5.2.5 on 2025-09-20 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0009_remove_gamehistory_reel_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="winnerhistory",
            name="claim_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="winnerhistory",
            name="game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="winner_histories",
                to="games.game",
            ),
        ),
        migrations.AlterField(
            model_name="winnerhistory",
            name="game_history",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="winners",
                to="games.gamehistory",
            ),
        ),
        migrations.AlterField(
            model_name="winnerhistory",
            name="reward_delivery_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="winnerhistory",
            name="reward_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="winnerhistory",
            name="reward_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="winnerhistory",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="winner_histories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
