# Generated by Django 5.2.5 on 2025-09-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0010_alter_winnerhistory_claim_deadline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="winnerhistory",
            name="forfeited",
            field=models.BooleanField(
                default=False, help_text="Marks if the reward was not claimed in time."
            ),
        ),
    ]
