# Generated by Django 5.2.5 on 2025-09-24 11:14

import core.utils.upload_paths
import core.utils.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0011_winnerhistory_forfeited"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="image",
            field=models.ImageField(
                help_text="Image representing the reward.",
                upload_to=core.utils.upload_paths.game_reward_upload_to,
                validators=[core.utils.validators.validate_image_file_size],
            ),
        ),
        migrations.AlterField(
            model_name="rewardmessage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.utils.upload_paths.reward_message_upload_to,
                validators=[core.utils.validators.validate_image_file_size],
            ),
        ),
        migrations.CreateModel(
            name="GameComplaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(help_text="Details of the complaint.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("resolved", "Resolved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        help_text="Current status of the complaint.",
                        max_length=20,
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the complaint was resolved or rejected.",
                        null=True,
                    ),
                ),
                (
                    "response",
                    models.TextField(
                        blank=True,
                        help_text="Response from the creator or admin regarding this complaint.",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user submitting the complaint (must be the winner).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_complaints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winner_history",
                    models.ForeignKey(
                        help_text="The winner who is filing the complaint.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaints",
                        to="games.winnerhistory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Game Complaint",
                "verbose_name_plural": "Game Complaints",
            },
        ),
    ]
