# Generated by Django 5.2.5 on 2025-09-24 15:26

import core.utils.upload_paths
import core.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0012_alter_game_image_alter_rewardmessage_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="first_prize_image",
            field=models.ImageField(
                blank=True,
                help_text="Image for first prize",
                null=True,
                upload_to=core.utils.upload_paths.game_reward_upload_to,
                validators=[core.utils.validators.validate_image_file_size],
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="first_prize_link",
            field=models.URLField(
                blank=True, help_text="Optional link for first prize", null=True
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="second_prize_image",
            field=models.ImageField(
                blank=True,
                help_text="Image for second prize",
                null=True,
                upload_to=core.utils.upload_paths.game_reward_upload_to,
                validators=[core.utils.validators.validate_image_file_size],
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="second_prize_link",
            field=models.URLField(
                blank=True, help_text="Optional link for second prize", null=True
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="third_prize_image",
            field=models.ImageField(
                blank=True,
                help_text="Image for third prize",
                null=True,
                upload_to=core.utils.upload_paths.game_reward_upload_to,
                validators=[core.utils.validators.validate_image_file_size],
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="third_prize_link",
            field=models.URLField(
                blank=True, help_text="Optional link for third prize", null=True
            ),
        ),
    ]
