# Generated by Django 5.2.5 on 2025-09-25 10:23

import core.utils.upload_paths
import core.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0013_game_first_prize_image_game_first_prize_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Game Banner/Cover image (used for promotion, not for prize)",
                null=True,
                upload_to=core.utils.upload_paths.game_reward_upload_to,
                validators=[core.utils.validators.validate_image_file_size],
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Optional: Website or sponsor link (visible to all players).",
                max_length=500,
                null=True,
            ),
        ),
    ]
