# Generated by Django 5.2.5 on 2025-09-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0014_alter_game_image_alter_game_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="reward_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cash", "Cash"),
                    ("digital", "Digital"),
                    ("product", "Product"),
                ],
                help_text="Optional: Type of first prize or all prizes if same kind.",
                max_length=20,
                null=True,
            ),
        ),
    ]
