# Generated by Django 5.2.5 on 2025-09-26 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0015_alter_game_reward_type"),
        ("reels", "0008_reel_is_ad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="reel",
            field=models.OneToOneField(
                blank=True,
                help_text="Optional reel linked to this game.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games",
                to="reels.reel",
            ),
        ),
    ]
