# Generated by Django 5.2.5 on 2025-09-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0016_alter_game_reel"),
    ]

    operations = [
        migrations.AddField(
            model_name="winningnumber",
            name="is_claimed",
            field=models.BooleanField(default=False),
        ),
    ]
