# Generated by Django 5.2.5 on 2025-09-27 13:06

import core.utils.upload_paths
import core.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0017_winningnumber_is_claimed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="first_prize_image",
            field=models.ImageField(
                default="game_rewards/default-placeholder.jpg",
                help_text="Image for first prize",
                upload_to=core.utils.upload_paths.game_reward_upload_to,
                validators=[core.utils.validators.validate_image_file_size],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gamehistory",
            name="reward_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="winnerhistory",
            name="reward_type",
            field=models.CharField(
                blank=True,
                help_text="Type of reward (cash/digital/product).",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="winningnumber",
            name="reward_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cash", "Cash"),
                    ("digital", "Digital"),
                    ("product", "Product"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
