# Generated by Django 5.2.5 on 2025-09-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0018_alter_game_first_prize_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamehistory",
            name="decrypted_winning_numbers",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
