# Generated by Django 5.2.5 on 2025-10-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0020_gamehistory_public_id_alter_gamehistory_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamehistory",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
