# Generated by Django 5.2.5 on 2025-10-04 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0021_alter_gamehistory_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        help_text="Winner position (1, 2, 3, etc.)"
                    ),
                ),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("digital", "Digital"),
                            ("product", "Product"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reward_title",
                    models.CharField(
                        help_text="Title or name of the reward", max_length=100
                    ),
                ),
                (
                    "reward_description",
                    models.TextField(
                        blank=True, help_text="Optional description", null=True
                    ),
                ),
                ("reward_link", models.URLField(blank=True, null=True)),
                ("is_claimed", models.BooleanField(default=False)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rewards",
                        to="games.game",
                    ),
                ),
            ],
            options={
                "unique_together": {("game", "position")},
            },
        ),
    ]
