# Generated by Django 5.2.5 on 2025-10-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0022_gamereward"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="winner_descriptions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Custom descriptions for winners 4,5,6...",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="winner_links",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Custom reward links for winners 4,5,6...",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="winner_titles",
            field=models.JSONField(
                blank=True, default=list, help_text="Custom titles for winners 4,5,6..."
            ),
        ),
    ]
