# Generated by Django 5.2.5 on 2025-10-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0023_game_winner_descriptions_game_winner_links_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="winnerhistory",
            name="received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="winnerhistory",
            name="reward_received",
            field=models.BooleanField(
                default=False, help_text="Winner confirms they received the reward."
            ),
        ),
    ]
