# Generated by Django 5.2.5 on 2025-10-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0024_winnerhistory_received_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rewardmessage",
            name="is_system_message",
            field=models.BooleanField(default=False),
        ),
    ]
