# Generated by Django 5.2.5 on 2025-10-07 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0025_rewardmessage_is_system_message"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rewardmessage",
            name="game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reward_messages",
                to="games.game",
            ),
        ),
        migrations.CreateModel(
            name="RewardChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_reward_chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="won_reward_chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("creator", "winner")},
            },
        ),
        migrations.AddField(
            model_name="rewardmessage",
            name="reward_chat",
            field=models.ForeignKey(
                blank=True,
                help_text="Chat thread between creator and winner",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="games.rewardchat",
            ),
        ),
    ]
