# Generated by Django 5.2.5 on 2025-10-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0026_rewardmessage_game_rewardchat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rewardmessage",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
