# Generated by Django 5.2.5 on 2025-10-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0027_rewardmessage_is_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="rewardmessage",
            name="is_delivered",
            field=models.BooleanField(default=False),
        ),
    ]
