# Generated by Django 5.2.5 on 2025-10-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0028_rewardmessage_is_delivered"),
    ]

    operations = [
        migrations.AddField(
            model_name="rewardchat",
            name="last_message_status",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
