# Generated by Django 5.2.5 on 2025-10-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0029_rewardchat_last_message_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="rewardmessage",
            name="receiver_online_after_delivery",
            field=models.BooleanField(default=False),
        ),
    ]
